openapi: 3.0.2
info:
  title: ScaledGitApp API
  version: 1.0.0
  description: ScaledGitApp API

paths:
  /api/env:
    summary: Gets the public API environment data
    get:
      operationId: getInfo
      summary: Gets the public API environment data
      responses:
        200:
          description:
            Contains public environment info that is still useful for developers
            when debugging issues
          content:
            application/json:
              schema:
                type: object
                required:
                  - gitHash
                  - tag
                properties:
                  gitHash:
                    description: Git commit hash
                    type: string
                  tag:
                    description: Build tag id
                    type: string
  /api/locales:
    summary: Gets translations based on a language
    get:
      operationId: getTranslationData
      summary: Gets translations based on a language
      parameters:
        - name: lng
          schema: { type: string }
          required: true
          in: query
        - name: ns
          schema: { type: string }
          required: true
          in: query
      responses:
        200:
          description: An i18next compatible json document containing the translation data
          content:
            application/json:
              schema:
                type: object
                # each additional property at this level is a language
                additionalProperties:
                  type: object
                  # each additional property at this level is a namespace
                  additionalProperties: { type: object, format: any }
