name: Build Docker

on:
  pull_request

env:
  registryLoginServer: 'example.com' # TODO
  imageName: 'scaledgitapp'
  dockerImageTag: 'ci-${{ github.run_number }}'

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v4

    - name: 'Build image'
      run: |
        docker build . -t $registryLoginServer/$imageName:$dockerImageTag --build-arg GITHASH=${{ github.sha }}
