name: Run all tests via `dotnet test``
on:
  pull_request:
    types: [edited, opened, reopened, synchronize, ready_for_review]

jobs:
  build:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/workflows/parts/cache/
      - name: 'Run tests'
        # Run tests that do not require git history. See https://learn.microsoft.com/en-us/dotnet/core/testing/selective-unit-tests?pivots=mstest
        run: |
          dotnet test --filter:"git-history!=required"
